---
abstract: 'Command-line ToolKit library (CTKlib). Command line interface (CLI)'
author:
  - 'Lepenkov Sergey (Serz Minus) <minus@mail333.com>'
build_requires:
  ExtUtils::MakeMaker: 6.6
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CTKlib
no_index:
  directory:
    - t
    - inc
recommends:
  DBI: 0
  Data::Dumper: 0
requires:
  Archive::Extract: 0.58
  Archive::Tar: 1.8
  Archive::Zip: 1.3
  Class::C3::Adopt::NEXT: 0.13
  Class::Singleton: 1.4
  Config::General: 2
  ExtUtils::MakeMaker: 6.6
  File::Copy: 2
  File::Path: 2
  File::Pid: 1
  File::Spec: 0.82
  HTTP::Headers: 5.8
  HTTP::Request: 5.8
  HTTP::Response: 5.8
  IO::Handle: 1.2
  IPC::Open3: 1
  LWP: 5.8
  LWP::MediaTypes: 6
  LWP::UserAgent: 5.8
  MIME::Base64: 3
  MIME::Lite: 3
  Moose: 2
  Net::FTP: 2.6
  Perl::OSType: 1
  Symbol: 1.05
  Term::ReadKey: 2.1
  Term::ReadLine: 1.04
  Test::More: 0.94
  Text::ParseWords: 3.27
  Time::HiRes: 1.97
  Time::Local: 1.2
  URI: 1.6
  XSLoader: 0.01
  YAML: 0.73
  namespace::autoclean: 0.13
  perl: 5.008001
resources:
  homepage: http://www.serzik.ru
  license: http://opensource.org/licenses/lgpl-license.php
  repository: http://svn.serzik.ru/CTKlib/trunk
version: 1.16
